# Generated by Django 5.1.3 on 2024-11-24 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('products', '0003_alter_products_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.carts')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
