# Generated by Django 5.1.3 on 2024-11-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocations', '0002_remove_geolocation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('seller_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('seller_city', models.CharField(max_length=200)),
                ('seller_state', models.CharField(max_length=200)),
                ('seller_zip_code_prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocations.geolocation')),
            ],
        ),
    ]
