# Generated by Django 5.1.3 on 2024-11-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderItems', '0001_initial'),
        ('products', '0003_alter_products_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItems',
        ),
    ]
