# Generated by Django 5.1.3 on 2024-11-23 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderItems', '0002_rename_orderitem_orderitems'),
        ('orders', '0002_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
    ]
