# Generated by Django 5.1.3 on 2024-11-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('customer_unique_id', models.CharField(max_length=200, unique=True)),
                ('customer_zip_code_prefix', models.IntegerField()),
                ('customer_city', models.CharField(max_length=200)),
                ('customer_state', models.CharField(max_length=200)),
            ],
        ),
    ]
