# Generated by Django 5.1.3 on 2024-11-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('geolocations', '0002_remove_geolocation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_zip_code_prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocations.geolocation'),
        ),
    ]
