# Generated by Django 5.1.3 on 2024-11-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='id',
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='geolocation_zip_code_prefix',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
