name: Run Unit Tests

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the `main` branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests targeting `main`

jobs:
  test:
    runs-on: ubuntu-latest  # The OS where the pipeline will execute
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v4  # Sets up Python in the pipeline
        with:
          python-version: 3.9  # Specify the Python version you use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Run Django tests
        run: |
          python manage.py test  # Run Django's test suite
