# Generated by Django 5.1.3 on 2024-11-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('seller_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('seller_zip_code_prefix', models.CharField(max_length=200)),
                ('seller_city', models.CharField(max_length=200)),
                ('seller_state', models.CharField(max_length=200)),
            ],
        ),
    ]
